# **Домашнее задание 3**

2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [240]:
import numpy as np
import matplotlib.pyplot as plt

In [241]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype=np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=np.float64)

In [242]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [243]:
X_st = X.copy()
X_st[:, 1] = standard_scale(X[:, 1])
X_st[:, 2] = standard_scale(X[:, 2])
X_st[:, 3] = standard_scale(X[:, 3])
X_st

array([[ 1.        , -0.70710678, -0.97958969, -0.89625816],
       [ 1.        , -0.70710678, -0.56713087, -0.89625816],
       [ 1.        , -0.35355339, -0.46401617,  0.38411064],
       [ 1.        ,  0.70710678, -0.77336028, -0.89625816],
       [ 1.        ,  0.        ,  0.97958969,  0.38411064],
       [ 1.        , -1.06066017, -0.36090146, -0.89625816],
       [ 1.        ,  0.70710678,  1.08270439,  1.66447944],
       [ 1.        ,  2.47487373,  2.11385144,  1.66447944],
       [ 1.        , -0.70710678, -1.08270439, -0.89625816],
       [ 1.        , -0.35355339,  0.05155735,  0.38411064]])

In [244]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [246]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [247]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [248]:
W = eval_model(X_st, y, iterations=950, eta=10)

0 [ 0.14172249 -2.84645945 -1.68657857  0.27823209] 0.760958797591889
95 [ 1.26075969 -6.80139995 -5.6257483  15.3762271 ] 0.21461297023068635
190 [ 2.90690328 -8.85101299 -8.42640769 19.40670778] 0.13293094891148885
285 [ 3.31504959 -9.78228813 -9.56439599 22.46116084] 0.11124466310787066
380 [  3.69066563 -10.69938068 -10.63186666  24.80480918] 0.10318963231969572
475 [  4.00951747 -11.47782288 -11.56344019  26.83100526] 0.09718922929874763
570 [  4.29035903 -12.1580876  -12.4045127   28.63843887] 0.09242381465270552
665 [  4.54395213 -12.76508529 -13.1813141   30.28694581] 0.08846496267351303
760 [  4.77717079 -13.31523188 -13.91046539  31.81515229] 0.08506604007106874
855 [  4.9946504  -13.81998375 -14.6029829   33.24927063] 0.08207466500687673


3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [250]:
def calc_pred_proba(w, X):
    y_pred_proba = sigmoid(np.dot(X, w))
    return y_pred_proba

In [251]:
y_pred_proba = calc_pred_proba(W, X_st)
y_pred_proba

array([3.18695118e-01, 8.63452878e-04, 1.00000000e+00, 3.39579389e-11,
       9.71730700e-01, 5.76089834e-03, 1.00000000e+00, 7.94920669e-03,
       6.92899115e-01, 1.00000000e+00])

4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [252]:
def calc_pred(w, X):
    y_pred = sigmoid(np.dot(X, w))

    for i in range(y_pred.shape[0]):
        if (y_pred[i] > 0.5): 
            y_pred[i] = 1
        elif (y_pred[i] <= 0.5):
            y_pred[i] = 0

    return y_pred

In [253]:
y_pred = calc_pred(W, X_st)
y_pred

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

6. Могла ли модель переобучиться? Почему?

In [254]:
W

array([  5.1975413 , -14.28296106, -15.25954145,  34.59380989])

Могла, при чрезмерном обучении и уменьшении logloss